apiVersion: v1
kind: Namespace
metadata:
  name: wty-istio
  labels:
    istio-injection: enabled 
---
apiVersion: v1
kind: Service
metadata:
  name: wtyfft-svc
  namespace: wty-istio
spec:
  selector:
    app: wtyfft-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wtyfft-deploy
  labels:
    app: wtyfft-deploy-label
  namespace: wty-istio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wtyfft-app
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/proxyCPU: 400m
        sidecar.istio.io/proxyCPULimit: 400m
        sidecar.istio.io/proxyMemory: 256Mi
        sidecar.istio.io/proxyMemoryLimit: 256Mi
      labels:
        app: wtyfft-app
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: wtyfft-app
      terminationGracePeriodSeconds: 45
      containers:
      - name: wtyfft-container-name
        image: registry.cn-hangzhou.aliyuncs.com/wtysos11/wty-fft:0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080   
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"   

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wtyfft-gateway
  namespace: wty-istio
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wtyfft-vs
  namespace: wty-istio
spec:
  hosts:
  - "*"
  gateways:
  - wtyfft-gateway
  http:
  - match:
    - uri:
        prefix: /fft
    - uri:
        exact: "/metrics"
    route:
    - destination:
        host: wtyfft-svc
        port:
          number: 8000

